version: "3.8"

services:
  frontend:
    build: .
    container_name: frontend
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=pruebasjaycom.shop,www.pruebasjaycom.shop
      - LETSENCRYPT_HOST=pruebasjaycom.shop,www.pruebasjaycom.shop
      - LETSENCRYPT_EMAIL=juanorejuela499@gmail.com
      - VITE_API_URL=https://api.pruebasjaycom.com
      - VITE_PAGE_URL=https://www.pruebasjaycom.com
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true
